[versions]
jdkRelease = "17"

agp = "8.13.2"
kotlin = "2.3.0"
androidx-room = "2.8.4"
androidx-lifecycle = "2.10.0"
accompanist = "0.37.3"
opto = "1.0.18"
protobuf = "4.33.2"
retrofit = "3.0.0"
dagger = "2.57.2"
libsu = "6.0.0"
refine = "4.4.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-baselineprofile = "androidx.baselineprofile:1.4.1"

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-ksp = "com.google.devtools.ksp:2.3.4"
google-protobuf = "com.google.protobuf:0.9.6"
cash-licensee = "app.cash.licensee:1.14.1"
rikka-refine = { id = "dev.rikka.tools.refine", version.ref = "refine" }
diffplug-spotless = "com.diffplug.spotless:8.1.0"

[libraries]
# AndroidX
androidx-activity-compose = "androidx.activity:activity-compose:1.12.2"
androidx-benchmark-macro-junit4 = "androidx.benchmark:benchmark-macro-junit4:1.4.1"
androidx-concurrent-futures = "androidx.concurrent:concurrent-futures:1.3.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.2.1"
androidx-core-animation = "androidx.core:core-animation:1.0.0"
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-datastore-preferences = "androidx.datastore:datastore-preferences:1.2.0"
androidx-dynamicanimation = "androidx.dynamicanimation:dynamicanimation:1.1.0"
androidx-espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
androidx-junit = "androidx.test.ext:junit:1.3.0"
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.9.6"
androidx-palette-ktx = "androidx.palette:palette-ktx:1.0.0"
androidx-preference-ktx = "androidx.preference:preference-ktx:1.2.1"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.4.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-slice-core = "androidx.slice:slice-core:1.1.0-alpha02"
androidx-uiautomator = "androidx.test.uiautomator:uiautomator:2.3.0"
androidx-window = "androidx.window:window:1.5.1"

# Compose
compose-bom = "androidx.compose:compose-bom:2025.12.00"
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material-icons = "androidx.compose.material:material-icons-extended:1.7.8"
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material3-windowSizeClass = { module = "androidx.compose.material3:material3-window-size-class" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }

# Dagger & Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }

# Accompanist
accompanist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# Opto
opto-core = { group = "com.patrykmichalik.opto", name = "core", version.ref = "opto" }
opto-compose = { group = "com.patrykmichalik.opto", name = "compose", version.ref = "opto" }
opto-domain = { group = "com.patrykmichalik.opto", name = "domain", version.ref = "opto" }

# Retrofit & OkHttp
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = "com.squareup.okhttp3:okhttp:5.3.2"

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }

# Kotlin
kotlin-androidExtensionRuntime = { module = "org.jetbrains.kotlin:kotlin-android-extensions-runtime", version.ref = "kotlin" }
kotlin-parcelizeRuntime = { module = "org.jetbrains.kotlin:kotlin-parcelize-runtime", version.ref = "kotlin" }
# KotlinX
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0"

protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }

# Other
android-desugarJdkLibs = "com.android.tools:desugar_jdk_libs:2.1.5"
airbnb-lottie = "com.airbnb.android:lottie:6.7.1"
chickenhook-restrictionbypass = "com.github.ChickenHook:RestrictionBypass:2.2"
coil-compose = "io.coil-kt:coil-compose:2.7.0"
google-material = "com.google.android.material:material:1.13.0"
hoko-blur = "io.github.hokofly:hoko-blur:1.5.5"
kdrag0n-colorkt = "dev.kdrag0n:colorkt:1.0.5"
libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
libsu-service = { group = "com.github.topjohnwu.libsu", name = "service", version.ref = "libsu" }
material-motion-compose = "io.github.fornewid:material-motion-compose-core:1.2.1"
persian-date = "com.github.samanzamani:PersianDate:1.7.1"
reorderable = "sh.calvin.reorderable:reorderable:2.5.1"
rikka-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "refine" }
rikka-annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "refine" }
rikka-refine-runtime = { group = "dev.rikka.tools.refine", name = "runtime", version.ref = "refine" }
smartspacer-sdk = "com.kieronquinn.smartspacer:sdk-client:1.1.2"
xdrop-fuzzywuzzy = "me.xdrop:fuzzywuzzy:1.4.0"
errorprone-annotations = "com.google.errorprone:error_prone_annotations:2.45.0"
composeRules = "io.nlopez.compose.rules:ktlint:0.5.2"

[bundles]
accompanist = ["accompanist-adaptive", "accompanist-drawablepainter", "accompanist-permissions"]
opto = ["opto-domain", "opto-core", "opto-compose"]
retrofit = ["retrofit-core", "retrofit-converter-kotlinx", "okhttp"]
room = ["room-runtime", "room-ktx"]
