[versions]
# From variables in original build.gradle
accompanist = "0.37.3"
benchmarkMacroJunit4 = "1.4.0"
coreAnimation = "1.0.0"
coreKtx = "1.17.0"
error_prone_annotations = "2.41.0"
espressoCore = "3.7.0"
junit = "1.3.0"
kotlinStdlibJdk7 = "2.2.10"
opto = "1.0.18"
protocVersion = "4.32.0"
retrofit = "3.0.0"
room = "2.7.2"

# Individual dependency versions
activityCompose = "1.10.1"
airbnbLottie = "6.6.7"
androidDesugar = "2.1.5"
coil = "2.7.0"
composeBom = "2025.08.01"
compose = "1.9.0"
composeMaterial = "1.9.0"
composeMaterial3 = "1.5.0-alpha03"
composeMaterialIcons = "1.7.8"
constraintlayout = "2.2.1"
dagger = "2.57.1"
datastore = "1.1.7"
dynamicanimation = "1.1.0"
fuzzywuzzy = "1.4.0"
googleMaterial = "1.13.0"
graphicsCore = "1.0.3"
graphicsPath = "1.0.1"
graphicsShapes = "1.1.0-beta01"
hokoBlur = "1.5.5"
javaxInject = "1"
kdrag0nColorkt = "1.0.5"
kotlinxCoroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
libsu = "6.0.0"
lifecycle = "2.9.3"
materialMotionCompose = "2.0.1"
navigationCompose = "2.9.3"
okhttp = "5.1.0"
palette = "1.0.0"
persianDate = "1.7.1"
preference = "1.2.1"
profileinstaller = "1.4.1"
recyclerview = "1.4.0"
reorderable = "2.5.1"
restrictionBypass = "2.2"
rikkaRefine = "4.4.0"
slice = "1.1.0-alpha02"
smartspacer = "1.1.2"
uiautomator = "2.3.0"
window = "1.4.0"

[libraries]
# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-benchmark-macro-junit4 = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-core-animation = { module = "androidx.core:core-animation", version.ref = "coreAnimation" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version.ref = "dynamicanimation" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-graphics-core = { group = "androidx.graphics", name = "graphics-core", version.ref = "graphicsCore" }
androidx-graphics-path = { group = "androidx.graphics", name = "graphics-path", version.ref = "graphicsPath" }
androidx-graphics-shapes = { group = "androidx.graphics", name = "graphics-shapes", version.ref = "graphicsShapes" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "palette" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-slice-core = { group = "androidx.slice", name = "slice-core", version.ref = "slice" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "composeMaterial" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIcons" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "composeMaterial3" }
compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose"}

# Dagger & Hilt
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
error_prone_annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "error_prone_annotations" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }

# Accompanist
accompanist-adaptive = { group = "com.google.accompanist", name = "accompanist-adaptive", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# Opto
kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdlibJdk7" }
opto-core = { group = "com.patrykmichalik.opto", name = "core", version.ref = "opto" }
opto-compose = { group = "com.patrykmichalik.opto", name = "compose", version.ref = "opto" }
opto-domain = { group = "com.patrykmichalik.opto", name = "domain", version.ref = "opto" }

# Retrofit & OkHttp
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protocVersion" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }

# Room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# KotlinX
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Other
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugar" }
airbnb-lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "airbnbLottie" }
chickenhook-restrictionbypass = { group = "com.github.ChickenHook", name = "RestrictionBypass", version.ref = "restrictionBypass" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "googleMaterial" }
hoko-blur = { group = "io.github.hokofly", name = "hoko-blur", version.ref = "hokoBlur" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject" }
kdrag0n-colorkt = { group = "dev.kdrag0n", name = "colorkt", version.ref = "kdrag0nColorkt" }
libsu-service = { group = "com.github.topjohnwu.libsu", name = "service", version.ref = "libsu" }
material-motion-compose = { group = "io.github.fornewid", name = "material-motion-compose-core", version.ref = "materialMotionCompose" }
persian-date = { group = "com.github.samanzamani", name = "PersianDate", version.ref = "persianDate" }
reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderable" }
rikka-annotation = { module = "dev.rikka.tools.refine:annotation", version.ref = "rikkaRefine" }
rikka-annotation-processor = { module = "dev.rikka.tools.refine:annotation-processor", version.ref = "rikkaRefine" }
rikka-refine-runtime = { group = "dev.rikka.tools.refine", name = "runtime", version.ref = "rikkaRefine" }
smartspacer-sdk = { group = "com.kieronquinn.smartspacer", name = "sdk-client", version.ref = "smartspacer" }
xdrop-fuzzywuzzy = { group = "me.xdrop", name = "fuzzywuzzy", version.ref = "fuzzywuzzy" }

[bundles]
accompanist = ["accompanist-adaptive", "accompanist-drawablepainter", "accompanist-permissions"]
graphics = ["androidx-graphics-core", "androidx-graphics-path", "androidx-graphics-shapes"]
opto = ["opto-domain", "opto-core", "opto-compose"]
retrofit = ["retrofit-core", "retrofit-converter-kotlinx", "okhttp"]
room = ["room-runtime", "room-ktx"]
